# Generated by Django 5.2 on 2025-06-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('forecast_date', models.DateField()),
                ('temperature_high', models.FloatField()),
                ('temperature_low', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'forecast_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('windspeed', models.FloatField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('weather_code', models.CharField(blank=True, max_length=50, null=True)),
                ('observed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'weather_observation',
                'indexes': [models.Index(fields=['city', 'observed_at'], name='weather_obs_city_c218e0_idx')],
            },
        ),
    ]
