# Generated by Django 5.2 on 2025-06-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_forecastdata_weatherobservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherobservation',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherobservation',
            name='pressure',
        ),
    ]
