# Generated by Django 5.2 on 2025-06-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_weatherobservation_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherobservation',
            name='weather_code',
        ),
    ]
